Repository ZTL-ARTCC/Current_Website, pull requests merged in 2024-09, with the labels that each got.

#648 NOISS: Add Mix cache tags
  public/js/app.js.LICENSE.txt
  resources/views/dashboard/admin/background-monitor.blade.php
  resources/views/dashboard/admin/realops/create.blade.php
  resources/views/dashboard/admin/realops/edit.blade.php
  resources/views/dashboard/admin/realops/index.blade.php
  resources/views/dashboard/admin/roster/edit.blade.php
  resources/views/dashboard/admin/roster/purge.blade.php
  resources/views/dashboard/controllers/airport.blade.php
  resources/views/dashboard/controllers/events/index.blade.php
  resources/views/dashboard/controllers/events/view.blade.php
  resources/views/dashboard/controllers/files.blade.php
  resources/views/dashboard/controllers/profile.blade.php
  resources/views/dashboard/controllers/roster.blade.php
  resources/views/dashboard/controllers/ticket.blade.php
  resources/views/dashboard/dashboard.blade.php
  resources/views/dashboard/training/edit_ticket.blade.php
  resources/views/dashboard/training/new_ticket.blade.php
  resources/views/dashboard/training/statistics.blade.php
  resources/views/dashboard/training/view_ticket.blade.php
  resources/views/inc/sidebar.blade.php
  resources/views/layouts/dashboard.blade.php
  resources/views/layouts/master.blade.php
  resources/views/site/airports/search.blade.php
  resources/views/site/airports/view.blade.php
  resources/views/site/files.blade.php
  resources/views/site/home.blade.php
  resources/views/site/pilot_guide_atl.blade.php
  resources/views/site/ramp.blade.php
  resources/views/site/realops.blade.php
  resources/views/site/roster.blade.php
  webpack.mix.js
Labels: tech debt

#649 NOISS: Create LICENSE
  LICENSE
Labels: tech debt

#654 NOISS: Fix training metrics totalizer
  app/Http/Controllers/ControllerDash.php
Labels: bug

#651 #603 Create live event information views
  app/Http/Controllers/AdminDash.php
  app/Http/Controllers/ControllerDash.php
  app/Http/Controllers/FrontController.php
  app/LiveEvent.php
  database/migrations/2024_09_13_160030_live_event_info.php
  resources/views/dashboard/admin/live.blade.php
  resources/views/dashboard/controllers/live_event_info.blade.php
  resources/views/dashboard/dashboard.blade.php
  resources/views/inc/navbar.blade.php
  resources/views/inc/sidebar.blade.php
  resources/views/site/live_event_info.blade.php
  routes/web.php
Labels: low priority

#665 NOISS: Fixes a typing bug in the LiveEvent model
  app/LiveEvent.php
Labels: bug, high priority

#670 NOISS: Enable E!A remote db access
  .env.example
  config/database.php
Labels: high priority

#661 #646 Create training team feedback system
  app/Http/Controllers/AdminDash.php
  app/Http/Controllers/ControllerDash.php
  app/Http/Controllers/FrontController.php
  app/Http/Controllers/TrainingDash.php
  app/TrainerFeedback.php
  database/migrations/2024_09_09_123300_trainer_feedback.php
  resources/assets/js/mix/trainerfeedback.js
  resources/views/dashboard/admin/trainer_feedback.blade.php
  resources/views/dashboard/controllers/profile.blade.php
  resources/views/dashboard/controllers/trainer_feedback.blade.php
  resources/views/dashboard/training/trainer_feedback.blade.php
  resources/views/inc/notifications.blade.php
  resources/views/inc/sidebar.blade.php
  resources/views/inc/trainer_feedback.blade.php
  resources/views/site/trainer_feedback.blade.php
  routes/web.php
Labels: high priority
