Repository ZTL-ARTCC/Current_Website, pull requests merged in 2024-04, with the labels that each got.

#534 #515 update atl pilot guide parking gates
  resources/views/site/pilot_guide_atl.blade.php
Labels: high priority

#533 NOISS: Fixes solo cert POST
  app/Http/Controllers/AdminDash.php
Labels: bug, high priority

#531 #513 Update realops email
  resources/views/emails/realops/assigned_flight.blade.php
  resources/views/emails/realops/bid.blade.php
  resources/views/emails/realops/flight_updated.blade.php
Labels: enhancement, high priority

#532 #526 Updates roster sort order to improve privacy
  app/Http/Controllers/RosterController.php
Labels: enhancement

#536 #514 Catch banner upload problems
  app/Http/Controllers/AdminDash.php
Labels: bug

#547 #518 Ckeditor update
  composer.json
  composer.lock
  package-lock.json
  package.json
  webpack.mix.js
Labels: tech debt

#559 NOISS CKEditor plugin deps v39
  package-lock.json
  package.json
Labels: bug, high priority

#560 NOISS Offset scheduled tasks
  app/Console/Kernel.php
Labels: high priority

#555 #551 Fixes solo cert API push
  app/Http/Controllers/AdminDash.php
Labels: bug

#554 #539 Removes codeshares from realops import task
  app/Console/Commands/FlightawareImport.php
Labels: enhancement

#563 NOISS Update visitor form policy requirements
  resources/views/site/visit.blade.php
Labels: policy
