Repository ZTL-ARTCC/Current_Website, pull requests merged in 2024-03, with the labels that each got.

#489 NOISS: Corrects download attribute
  resources/views/dashboard/controllers/files.blade.php
Labels: bug

#490 NOISS: Updates EA link for training staff
  resources/views/inc/sidebar.blade.php
Labels: bug

#504 #498 Add privacy flag to user profile
  resources/views/dashboard/controllers/profile.blade.php
Labels: enhancement, good first issue

#516 #512 Fix minor JS errors
  resources/assets/js/mix/pilots_guide.js
Labels: bug

#522 NOISS: Fix capitalization errors in tooltip
  resources/views/dashboard/controllers/profile.blade.php
Labels: php

#525 NOISS: Fix position id typo
  app/Console/Commands/UploadTrainingTickets.php
Labels: bug

#523 NOISS fix flightaware import task
  app/Console/Commands/FlightawareImport.php
Labels: high priority
