Repository ZTL-ARTCC/Current_Website, pull requests merged in 2024-05, with the labels that each got.

#570 #548 Update ZTL holiday logos
  public/photos/logos/ztl_logo_beach-black.png
  public/photos/logos/ztl_logo_beach-white.png
  public/photos/logos/ztl_logo_fireworks-black.png
  public/photos/logos/ztl_logo_fireworks-white.png
  public/photos/logos/ztl_logo_flag-black.png
  public/photos/logos/ztl_logo_flag-white.png
  public/photos/logos/ztl_logo_halloween-black.png
  public/photos/logos/ztl_logo_halloween-white.png
  public/photos/logos/ztl_logo_santa-black.png
  public/photos/logos/ztl_logo_santa-white.png
  public/photos/logos/ztl_logo_spring-black.png
  public/photos/logos/ztl_logo_spring-white.png
  public/photos/logos/ztl_logo_turkey-black.png
  public/photos/logos/ztl_logo_turkey-white.png
Labels: medium priority

#571 #546 Update login redirects for realops
  app/Http/Controllers/Auth/LoginController.php
Labels: low priority

#573 NOISS Fix bugs in controller edit
  app/Http/Controllers/AdminDash.php
Labels: bug, high priority

#575 #464 blank input allow reject visitor throws error
  app/Http/Controllers/AdminDash.php
Labels: bug, high priority
