Repository ZTL-ARTCC/Current_Website, pull requests merged in 2024-10, with the labels that each got.

#675 NOISS: Prevent students from seeing draft tickets
  app/Http/Controllers/ControllerDash.php
Labels: high priority

#674 NOISS: Normalize draft ticket view with new ticket view
  resources/views/dashboard/training/edit_ticket.blade.php
Labels: high priority

#680 NOISS: Fix training reminder emails
  resources/views/emails/training_reminder.blade.php
Labels: bug, high priority

#650 #540, #541 Realops fix callsign issues
  app/Console/Commands/FlightawareImport.php
  app/Exports/RealopsExport.php
  app/Http/Controllers/RealopsController.php
  app/Importers/RealopsFlightImporter.php
  app/RealopsFlight.php
  database/migrations/2024_09_13_143830_realops_flight_add_callsign.php
  resources/views/dashboard/admin/realops/create.blade.php
  resources/views/dashboard/admin/realops/edit.blade.php
  resources/views/dashboard/admin/realops/index.blade.php
  resources/views/emails/realops/assigned_flight.blade.php
  resources/views/emails/realops/bid.blade.php
  resources/views/emails/realops/flight_updated.blade.php
  resources/views/site/realops.blade.php
Labels: low priority

#681 #671 Allow deleting of draft training tickets
  app/Http/Controllers/TrainingDash.php
  resources/views/dashboard/training/edit_ticket.blade.php
Labels: medium priority
