Repository ZTL-ARTCC/Current_Website, pull requests merged in 2025-04, with the labels that each got.

#742 #741 Use Laravel 12 framework
  composer.json
  composer.lock
Labels: tech debt

#751 #749 Fix local hero challenge title display error
  app/Http/Controllers/ControllerDash.php
Labels: bug

#752 #685 Creates student comment emails
  app/Http/Controllers/TrainingDash.php
  app/Mail/StudentComment.php
  resources/views/emails/student_comment.blade.php
Labels: enhancement

#759 #755 Reassign Existing Permalink
  app/Http/Controllers/AdminDash.php
  resources/assets/js/mix/permalink_field.js
  resources/views/dashboard/admin/files/upload.blade.php
Labels: enhancement
